site_name: Atomix
site_url: https://atomix.io
copyright: Copyright © 2022 Intel Corporation
repo_url: https://github.com/atomix

plugins:
  - search
  - minify:
      minify_html: true

theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/logo.png
  logo: images/logo.png
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - user-guide/index.md
      - Architecture: user-guide/architecture.md
      - Application Development:
          - user-guide/development/index.md
          - Go: user-guide/development/go.md
          - Java: user-guide/development/java.md
          - Atoms:
              - user-guide/development/atoms/index.md
              - Counter: user-guide/development/atoms/counter.md
              - CounterMap: user-guide/development/atoms/countermap.md
              - IndexedMap: user-guide/development/atoms/indexedmap.md
              - LeaderElection: user-guide/development/atoms/election.md
              - List: user-guide/development/atoms/list.md
              - Lock: user-guide/development/atoms/lock.md
              - Map: user-guide/development/atoms/map.md
              - MultiMap: user-guide/development/atoms/multimap.md
              - Set: user-guide/development/atoms/set.md
              - Topic: user-guide/development/atoms/topic.md
              - Value: user-guide/development/atoms/value.md
      - Deployment and Operations:
          - user-guide/deployment/index.md
          - Installation: user-guide/deployment/installation.md
          - Storage Profiles: user-guide/deployment/storage-profiles.md
          - Data Stores:
              - user-guide/deployment/data-stores/index.md
              - ConsensusStore: user-guide/deployment/data-stores/consensus.md
              - GossipStore: user-guide/deployment/data-stores/gossip.md
              - PodMemoryStore: user-guide/deployment/data-stores/pod-memory.md
              - SharedMemoryStore: user-guide/deployment/data-stores/shared-memory.md
  - Contributor Guide:
      - contributor-guide/index.md
      - SDKs: contributor-guide/sdk.md
      - Data stores: contributor-guide/data-stores.md
  - API Reference:
      - reference/index.md
      - Go: https://pkg.go.dev/github.com/atomix/go-sdk
      - Protobuf:
          - atomix.runtime.counter.v1: reference/api/atomix/runtime/counter/v1/counter.md
          - atomix.runtime.countermap.v1: reference/api/atomix/runtime/countermap/v1/countermap.md
          - atomix.runtime.election.v1: reference/api/atomix/runtime/election/v1/election.md
          - atomix.runtime.indexedmap.v1: reference/api/atomix/runtime/indexedmap/v1/indexedmap.md
          - atomix.runtime.list.v1: reference/api/atomix/runtime/list/v1/list.md
          - atomix.runtime.lock.v1: reference/api/atomix/runtime/lock/v1/lock.md
          - atomix.runtime.map.v1: reference/api/atomix/runtime/map/v1/map.md
          - atomix.runtime.multimap.v1: reference/api/atomix/runtime/multimap/v1/multimap.md
          - atomix.runtime.v1: reference/api/atomix/runtime/v1/primitive.md
          - atomix.runtime.set.v1: reference/api/atomix/runtime/set/v1/set.md
          - atomix.runtime.topic.v1: reference/api/atomix/runtime/topic/v1/topic.md
          - atomix.runtime.value.v1: reference/api/atomix/runtime/value/v1/value.md
  - Resources:
      - resources/index.md
      - License: resources/license.md

markdown_extensions:
  - toc:
      permalink: true
      title: "Table of contents"
  - smarty
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/atomix
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/atomix/repositories
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/atomixio/shared_invite/enQtNDgzNjA5MjMyMDUxLTVmMThjZDcxZDE3ZmU4ZGYwZTc2MGJiYjVjMjFkOWMyNmVjYTc5YjExYTZiOWFjODlkYmE2MjNjYzZhNjU2MjY
    - icon: fontawesome/brands/java
      link: https://github.com/atomix/java-sdk
    - icon: fontawesome/brands/golang
      link: https://github.com/atomix/go-sdk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/atomixio
  generator: false
  version:
    provider: mike