site_name: Atomix
site_url: https://atomix.io
copyright: Copyright © 2022 Intel Corporation
repo_url: https://github.com/atomix

plugins:
  - search
  - import
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - minify:
      minify_html: true

theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
      - concepts/index.md
  - User Guide:
      - user-guide/index.md
      - Primitives:
          - Counter: user-guide/primitives/counter.md
          - Map: user-guide/primitives/map.md
      - Drivers:
          - user-guide/drivers/index.md
          - Local: '!import url(https://raw.githubusercontent.com/atomix/drivers/master/local/README.md) path(user-guide/drivers/local.md)'
          - Multi-Raft: '!import url(https://raw.githubusercontent.com/atomix/drivers/master/multi-raft/README.md) path(user-guide/drivers/muti-raft.md)'
      - SDKs:
          - user-guide/clients/index.md
          - Go: '!import icon(fontawesome/brands/golang) url(https://raw.githubusercontent.com/atomix/go-client/runtime-generics/README.md) path(user-guide/clients/go.md)'
          - Java: '!import icon(fontawesome/brands/java) url(https://raw.githubusercontent.com/atomix/java-client/master/README.md) path(user-guide/clients/java.md)'
  - Contributor Guide:
      - contributor-guide/index.md
  - Reference:
      - reference/index.md
      - Protobuf API:
          - atomix.counter.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/counter/v1/counter.md) path(reference/api/counter/v1/counter.md)'
          - atomix.election.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/election/v1/election.md) path(reference/api/election/v1/election.md)'
          - atomix.indexed_map.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/indexed_map/v1/indexed_map.md) path(reference/api/indexed_map/v1/indexed_map.md)'
          - atomix.list.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/list/v1/list.md) path(reference/api/list/v1/list.md)'
          - atomix.lock.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/lock/v1/lock.md) path(reference/api/lock/v1/lock.md)'
          - atomix.map.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/map/v1/map.md) path(reference/api/map/v1/map.md)'
          - atomix.runtime.v1:
                  - Application: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/runtime/v1/application.md) path(reference/api/runtime/v1/application.md)'
                  - Cluster: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/runtime/v1/cluster.md) path(reference/api/runtime/v1/cluster.md)'
                  - Driver: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/runtime/v1/driver.md) path(reference/api/runtime/v1/driver.md)'
                  - Primitive: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/runtime/v1/primitive.md) path(reference/api/runtime/v1/primitive.md)'
                  - Runtime: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/runtime/v1/runtime.md) path(reference/api/runtime/v1/runtime.md)'
          - atomix.set.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/set/v1/set.md) path(reference/api/set/v1/set.md)'
          - atomix.time.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/time/v1/timestamp.md) path(reference/api/time/v1/timestamp.md)'
          - atomix.topic.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/topic/v1/topic.md) path(reference/api/topic/v1/topic.md)'
          - atomix.value.v1: '!import hide(toc) url(https://raw.githubusercontent.com/atomix/runtime/runtime-api-revert/api/atomix/value/v1/value.md) path(reference/api/value/v1/value.md)'
  - About:
      - about/index.md
      - License: about/license.md

markdown_extensions:
  - toc:
      permalink: true
      title: "Table of contents"
  - smarty
  - meta
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/atomix
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/atomix/repositories
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/atomixio/shared_invite/enQtNDgzNjA5MjMyMDUxLTVmMThjZDcxZDE3ZmU4ZGYwZTc2MGJiYjVjMjFkOWMyNmVjYTc5YjExYTZiOWFjODlkYmE2MjNjYzZhNjU2MjY
    - icon: fontawesome/brands/java
      link: https://github.com/atomix/java-client
    - icon: fontawesome/brands/golang
      link: https://github.com/atomix/go-client
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/atomixio
  generator: false
  version:
    provider: mike
